### ISSUE TITLE
How to stop the program?

### ISSUE THREAD

**Issue by mzahar** [Arriven/db1000n#124]
Is there a way to stop program? Or I need only uninstall it to stop?
Device: Mac Book Pro Intel

**Comment by iamtodor** [comment]
@mzahar you run it as binary file?

**Comment by Devaniti** [comment]
If you don't see terminal window with program then it's not running

**Comment by Arriven** [comment]
Anything that would work for a regular program would work here (I'm assuming you use binary install which is described in the instruction for users). If you see the terminal where the program is running you can stop it by pressing Ctrl+C. Otherwise you can use Activity Monitor (similar to Task Manager on Windows AFAIK) to check if the program is running and stop it
