### ISSUE TITLE
Performance and multithreading

### ISSUE THREAD

**Issue by Devaniti** [Arriven/db1000n#136]
On my machine, even with free VPN, I can get at least 10x performance by launching multiple instances
We need to implement multithreading, so it can utilize all available resources
Will try to do myself, but since I'm not that good at Golang I may need some help

**Comment by Devaniti** [comment]
ok, it seems that there's multithreading, but there's still bottleneck somewhere

**Comment by Devaniti** [comment]
this is the offender,
`for i := 0; i < jobDesc.Count; i++ {`
`jobDesc.Count` is just too low

**Comment by Arriven** [comment]
@Devaniti I wouldn't call it a bottleneck but rather a design limitation. The app is configurable to generate set amount of traffic (controlled by the number of targets, their type, and attack interval for each of them). The main reason it works that way is because there are two main types of ddos:

- Straightforward load generation (easy to implement, easy to defend from) - as effective as the amount of raw traffic you can generate
- Actual denial of service that aims to remain as undetected as possible by simulating plausible traffic and hitting concrete vulnerabilities in the target (or targets). This type of ddos doesn't require a lot of traffic and thus is mostly limited by the amount of clients generating this type of load (or rather unique IPs)

Performance tweaks would improve the effectiveness of first ddos type but all the experts I had a chance talking to yet say that second way is a lot more efficient in the long term so I'm mainly focusing my efforts on it. If you have an idea on how to make it possible to provide a configuration or commandline option to allow using all the resources available to the system - feel free to create a PR, it wouldn't hurt as long as it's optional

**Comment by lomchik** [comment]
So probably we should update targets to attack for example search endpoints  like https://www.rt.com/search?q=stupid+russian+bitches.
