### ISSUE TITLE
Strange network traffic statistics

### ISSUE THREAD

**Issue by novikor** [Arriven/db1000n#201]
**Preconditions**:
Linux mint + docker

**Steps to reproduce:**
run `docker run --rm ghcr.io/arriven/db1000n:latest`

**Expected result:**
Incoming traffic in less than outcoming one

**Actual result:**
![image](https://user-images.githubusercontent.com/26086561/156987976-3ff39cdd-b4d3-4a8a-af13-6daff49ec400.png)

I have checked older versions too - the behavior is the same

**Comment by Arriven** [comment]
I'll check out the config in a minute but I'd assume that this means that targets it attacks don't use any DDoS protection and actually process and respond to requests. I'm not completely sure but it would mean that the attack is extremely effective since we're doing exactly what we want to do - make target spend as much of its resources on our load as we can.

Another possibility is that someone is trying to DDoS you back but I rather doubt it and even in that case I'd say it's a benefit for us

**Comment by Devaniti** [comment]
ddosing you back is certainly not happening here, you can clearly see that incoming traffic triggered by starting the app
so I'd too say that it works as expected

**Comment by Arriven** [comment]
I think I know which attack is triggering this behavior and this graph is a good indication that the attack is not detected as DDoS by the receiving party. Having inspected the attack I also suspect that the configuration of this attack can be improved further now that we know the attack is not detected

If you want to understand more what is happening - try running something like `curl https://raw.githubusercontent.com/Arriven/db1000n/main/testconfig.json` couple of times in a container and inspecting its traffic. You should see a similar network graph (probably with lower numbers but still). This is just an example and reality is a lot more complex but hope it helps

**Comment by novikor** [comment]
@Arriven , thank you!
