### ISSUE TITLE
Network traffic limitation

### ISSUE THREAD

**Issue by vovagorodok** [Arriven/db1000n#294]
There is any flag or config to limit network traffic? It's not possible to work at network from other PC when ddoser is turned on. Pages are not responsible. If it's possible to limit then will be nice to add this info to documentation. For me personally docker case is interesting one

**Comment by bitshape** [comment]
Make sure your PC is connected over Ethernet to your router if it isn't.

If you can setup Docker with VPN, it might be worth trying. VPN is unlikely to be as fast as your main connection so that's both benefit and downside. But more importantly, since your traffic will be encapsulated over TCP/UDP VPN connection, you're less likely to suffer from connection limit, which is what you're describing sounds like to me.

Finally you can try using advanced configuration even without Docker:

`./db1000n -c https://raw.githubusercontent.com/db1000n-coordinators/LoadTestConfig/main/config.v0.7.adv.json`

**Comment by Liovareg** [comment]
You can limit cpu usage per docker container with "--cpus=0.1" param, this will therefore limit net usage as well.

**Comment by Arriven** [comment]
Apart from docker solution you can also use `--min-interval` to introduce artificial rate limiting to attacks (see --help for more details)
