### ISSUE TITLE
All db1000n targets are refusing connection. WAIDW?

### ISSUE THREAD

**Issue by s7aycool** [Arriven/db1000n#365]
debug log:
https://gist.github.com/s7aycool/3d51f00d45b5c747ed46288f7d6bbbf5

**Comment by Lagovas** [comment]
probably russian resources updated their web servers and validate Host header ))
for example `141.105.69.219` now refuses connection but works as `https://infox.sg`. 
So, maybe @Arriven should update default config and use domains instead of IPs. Or if main goal was to increase performance and avoid extra DNS queries, then we should specify manually expected Host in http request and TLS config's ServerName - https://github.com/golang/go/issues/22704.
But better to resolve once at start of job, then manually craft http request and TLS config and make requests using IP. Becase as I understand, golang doesn't cache dns results

**Comment by s7aycool** [comment]
Any updates? I see a lot of people who are having troubles with that

**Comment by Arriven** [comment]
@s7aycool current config is using both hostname based targets (around 60-70% of them) and IP based ones. Successful attacks don't spam error logs so it might be not really noticeable but the overall situation should be better

**Comment by s7aycool** [comment]
@Arriven got you. Nevertheless, to be able to see % of successful attacks will be nice. Some kind of counter maybe?

**Comment by Arriven** [comment]
I thought about that but properly tracking success rate requires a separate set of tools that could turn out to be more complex than this one. I think it's better to use them instead if you want to have a better picture of what's happening with targets

**Comment by Arriven** [comment]
There are a counter with the amount of traffic generated by the app and the amount of traffic for which a target has returned some sort of response but not all attacks support that (some of them are fire and forget by design)

**Comment by crocangIt** [comment]
@Arriven Hi,
On all VM's I have similar status: see Received and Response rate
Just restarted this one :
---------Traffic stats---------
 [     Generated ] 815.62 MB | 855236188 bytes
 [      Received ]   0.05 MB |     49936 bytes
 [ Response rate ]    0.0%
-------------------------------
As far as I know this started today. Since yesterday I am using: db1000n-v0.7.12-windows-amd64
Using different VPN locations: UAE. Egypt, Denmark...

**Comment by Arriven** [comment]
From what I can tell - most alternatives tell their users that this behavior means that the targets are down (and that's actually quite likely the case). Ideally we'd want to confirm this by trying to access targets in non-disruptive way and see if they respond

**Comment by crocangIt** [comment]
> From what I can tell - most alternatives tell their users that this behavior means that the targets are down (and that's actually quite likely the case). Ideally we'd want to confirm this by trying to access targets in non-disruptive way and see if they respond

Hi, last night I checked using RU VPN and all targets were down.
This morning I see under the "Response rate" of db100n:
UAE:  [ Response rate ] 18.9%
Denmark: [ Response rate ] 41.9%
Sweden: VPN provider1 [ Response rate ] 88.6% ; VPN provider2 [ Response rate ] 90.3%

Shell I switch all to Sweden?
Or it is better to spread the VPN locations?
