### ISSUE TITLE
Linux version(amd64) doesn't start.

### ISSUE THREAD

**Issue by osomfinch** [Arriven/db1000n#369]
Hi! first of all, I'm very grateful for your work. It's amazing, really!

Now, the Linux version won't start on ZorinOS(Ubuntu). I download it, unpack it, and then I try to run it and nothing happens. What could be the problem?

Interestingly, it seems to be working via wine just fine.

**Comment by Arriven** [comment]
does it output any logs?

**Comment by osomfinch** [comment]
> does it output any logs?

No. The app simply doesn't start. I press on it and nothing happens.

**Comment by sivillakonski** [comment]
@osomfinch, - " I press on it" - I do understand that you are trying to run it thru the file manager, correct?
Mind if I ask you to try to run it in a bit different way?

Open the terminal and navigate to the directory where you have your DB1000N executable file unpacked.
Then run the command in the terminal:
~~~bash
./db1000n
~~~

For example:
![Screenshot 2022-03-19 at 13 10 14](https://user-images.githubusercontent.com/100792803/159131317-e0d8453a-35f9-4a12-bc4b-1334ab8bfbd9.png)

Please, ignore this message if tried this already. I don't have all the details, so it's rather my assumption

**Comment by osomfinch** [comment]
> Open the terminal and navigate...

Yes, it works now. Thank you!

But I don't see any reason to use it instead of the Windows' version now. Cause with the Windows version I open it in two clicks, and with the Linux version I have to open the terminal and type a tone of things. 

Since we know that the app works and the problem is in GNOME, is there a way to make GNOME open it via the GUI?

**Comment by sivillakonski** [comment]
@osomfinch, glad to hear that!

Basically, this is CLI oriented utility that runs, in most cases, on the machines without the User Interface at all. Since it's fully automatic tool that receives configurations from the remote source - there is no need for user to see any kind of UI controls.

You can try to create the Desktop link like described here (https://askubuntu.com/questions/436891/create-a-desktop-file-that-opens-and-execute-a-command-in-a-terminal)
~~~
[Desktop Entry]
Version=1.0
Name=Test        
Comment=Test the terminal running a command inside it
Exec=gnome-terminal -e "/path/to/my/db1000n"
Icon=utilities-terminal
Terminal=false
Type=Application
Categories=Application;
~~~

**Comment by osomfinch** [comment]
> Basically, this is CLI oriented utility that runs...

Well, as we can see, I need it to be able to be run through GUI. It just goes to show how outdated the modern Linux desktop environment paradigm is. Especially it concerns GNOME. But it's a completely different topic.

Thank you for your help!
