### ISSUE TITLE
Encrypted jobs and Prometheus stats

### ISSUE THREAD

**Issue by bitshape** [Arriven/db1000n#399]
Assuming https://github.com/Arriven/db1000n/commit/620ba375b1ba5c13e439c0dfb88f3e2d0a3868b3 was removed so that wouldn't be possible to inspect encrypted config by polling from Prometheus server, this still leaves a possibility of indirectly observing encrypted config by setting up own Prometheus push server and overriding `PROMETHEUS_GATEWAYS` to be non-default.

If this is correct assumption, maybe encrypted jobs shouldn't use Prometheus push gateway either.

**Comment by Arriven** [comment]
the thing is that we can't secure everything and it's just a question of slowing down those who want to get access to the encrypted config. You need to set up your own prometheus cluster in order to leverage this data leak but at that point you can probably get more info by inspecting the traffic generated by the app with some external tools. As for disabling polling endpoint - I've removed that because it was simpler than the "inspect traffic" baseline
