### ISSUE TITLE
Please create a support group

### ISSUE THREAD

**Issue by ignitedevua** [Arriven/db1000n#410]
a lot of people faced with problems like this: 
<pre>
!Атака проводиться успішно! Руський воєнний корабль іди нахуй!
!Attack is successful! Russian warship, go fuck yourself!
---------Traffic stats---------
 [     Generated ] 39643.71 MB | 41569447185 bytes
 [      Received ]     0.09 MB |       96869 bytes
 [ Response rate ]      0.0%
-------------------------------
</pre>
why 0.0% ? how to fix? why so low? 

Please create a support group in the telegram

**Comment by Arriven** [comment]
Low response rates usually mean that targets can't manage the load we're producing

**Comment by Arriven** [comment]
Probably best to just add that last sentence to FAQ

As for support group - there no groups dedicated to just this tool alone but considering the spread of it you can probably get some initial help in [IT Army of Ukraine](https://t.me/itarmyofukraine2022) (I'll probably add this to the config repo since it's more relevant there)

**Comment by Arriven** [comment]
fe0c8c90e1178e57408031c7e85baf1cb1352f79 for the FAQ part

**Comment by Arriven** [comment]
Enabled github discussions for community help
