### ISSUE TITLE
-local-address do not works with ipv6 addresses

### ISSUE THREAD

**Issue by Sfinx** [Arriven/db1000n#521]
```
./db1000n -local-address 2001:xxx...
```

just select first ipv4 interface

**Comment by Arriven** [comment]
weird, it seems to be working for me, but it needs a full address (i.e. `e80::xxxx:xxxx:xxxx:xxxx/64`). I don't have an interface that is only exposing ipv6 address though so not 100% sure it works in all cases

**Comment by Arriven** [comment]
In order to use ipv6 interface this way you also need to provide an ipv6 zone (interface name) because in case of ipv6 you can have same link address for multiple interfaces. I had to add support for proper parsing of that (incoming in 0.8.33) but in order to use it you should specify something like `-local-address fe80::xxxx:xxxx:xxxx:xxxx%wlp0s20f3` where `wlp0s20f3` is the name of your interface

**Comment by Arriven** [comment]
weird, it seems to be working for me, let me check on my remote server if it's still up

**Comment by Arriven** [comment]
yeah, it seems to pickup the right interface, although my home network doesn't support ipv6 so I just get `network unreachable` (ping displays the same thing)

**Comment by deputinizer** [comment]
For me `%interface` doesn't work either.
`./db1000n -local-address 10.2.2.2%wlan1`

**Comment by Arriven** [comment]
@deputinizer %interface should only be specified for ipv6 addresses and it's designed that way because you can have the same ipv6 address for multiple interfaces

**Comment by deputinizer** [comment]
@Sfinx Probably fixed in a7edd0071ee129712fe3ebdf643a75e24c3f1a0a

**Comment by Sfinx** [comment]
Works with ipv6 ! But still small bug that was not present at pre 0.8x series - countrycheker still uses ipv4 addressing for country check :

```
utils/countrychecker.go:78      location info   {"country": ....
```

**Comment by deputinizer** [comment]
@Sfinx Fixed IPv6 and countrychecker
