### ISSUE TITLE
Error when pulling docker image

### ISSUE THREAD

**Issue by sentinalll** [arriven/db1000n#541]
## Expected Behavior
Docker image pull successful

## Actual Behavior
error pulling image configuration: download failed after attempts=1: unknown blob

## Steps to Reproduce the Problem

  1. Try pulling the docker image
  2.
  3.

## Specifications

  - Version:
  - Platform:
  - Subsystem:

**Comment by arriven** [comment]
ghcr links got broken when I tweaked the account name (Arriven -> arriven, case sensitivity doesn't and shouldn't affect URLs at all, every other related functionality like working with the repo via ssh/https works fine which is weird since docker image was the only part of repo that used lowercase variant from the beginning). I triggered a new version and that seems to have fixed it
