### ISSUE TITLE
Security issue because of public repo

### ISSUE THREAD

**Issue by makbar1234** [Arriven/db1000n#55]
Росіяни чи про-російськи можуть взяти ваш код, підправити шлях до конфігу - і досити українські ресурси!

сховайте код, не робіть роботу за окупанта
роздавайте докер імідж і то краще б якось обережно імідж робити, щоб код не взяли звідти

**Comment by Zip753** [comment]
з одного боку так, але з іншого боку і так чат в телеграмі відкритий, тож великої секретності ми не заховаємо в будь якому випадку

**Comment by Arriven** [comment]
In theory yes, in reality it is a question of organization and resources and for now the pros of having open source approach (trust of users and collaboration: I think around 10% of the work here is done by people who just decided to help and could do it because it's open but the number will grow as the app gets more popular) outweigh the cons. Also it's not a unique idea and there are other open source alternatives which only need a day-two of hard work to match this app so there's not too much sense in hiding it.

**Comment by kuzm1ch** [comment]
completely agree to have it opensource. At list people should be aware what they are running on their machines.

**Comment by makbar1234** [comment]
people in channel are still coordinating and running soft manually.
they are confused that this repo is not synched with the targets admins set. So, the pros are not working because of that.
Targets may change within hours but config is not updated with it. Could you fix that?
as for users' trust, I understand this but the weak point is that people who understands that don't always need such democratic tools, they are able to run some better scripts and setup linux. non-programming people don't actually understand what open-source means, they don't care and just trust admins, they blindly paste any commands they are told.

**Comment by Arriven** [comment]
@makbar1234 the process of finding and training admins to use this took some time because of war in the country and regular need for both me and admins to run to the shelter due to air hazards. First admin is already ready since 40 minutes ago and the process should get better now. Sorry for the inconvenience
