### ISSUE TITLE
Хто кординує дії?? 

### ISSUE THREAD

**Issue by KhalupiakYaroslav** [Arriven/db1000n#77]
Отримав посилання на image від кібер козаків, але хости які атакує скрипт не співпадають з тим що вони пишуть у себе в групі

**Comment by Arriven** [comment]
Yeah, we're still organizing the process with admins (we need to set up a training but human interactions take time especially since most of us are in Ukraine and have to regularly run to shelter). ETA should be somewhere today if no force-majors take place. You can also take part in that by proposing pull-requests to https://github.com/db1000n-coordinators/LoadTestConfig
